### ISSUE TITLE
stop and load new video

### ISSUE THREAD

**Issue by oluwabajio** [rtoshiro/FullscreenVideoView#16]
Hello, please help me urgently, what code do i use to load a new video and play when a video is already playing before.

**Comment by rtoshiro** [comment]
hi @oluwabajio 
Well, you can copy the application example MainActivity.java:

``` java
videoLayout = (FullscreenVideoLayout) findViewById(R.id.videoview);
videoLayout.setActivity(this);
videoLayout.setShouldAutoplay(false);
Uri videoUri = Uri.parse("http://techslides.com/demos/sample-videos/small.mp4");
try {
    videoLayout.setVideoURI(videoUri);
} catch (IOException e) {
    e.printStackTrace();
}
```

I hope it helps.

**Comment by oluwabajio** [comment]
Thanks for your response, That code works fine if no video was playing at all, but in a situation where a video is already playing and you want to play another one, it shows illegalstate exception at this place 

```
throw new IllegalStateException("FullscreenVideoView Invalid State: " + currentState); 
```

inside setvideourl

 public void setVideoURI(Uri uri) throws IOException, IllegalStateException, SecurityException, IllegalArgumentException, RuntimeException {
        if (mediaPlayer != null) {
            if (currentState != State.IDLE)
                throw new IllegalStateException("FullscreenVideoView Invalid State: " + currentState);

```
        mediaPlayer.setDataSource(context, uri);

        currentState = State.INITIALIZED;
        prepare();
    } else throw new RuntimeException("Media Player is not initialized");
}
```

**Comment by rtoshiro** [comment]
Oh, sorry, I didn't pay attention about videos that were already playing. You are right. That's because it follows the MediaPlayer states table.
In that case, I suggest you to call "reset()" before setting a new data source.
Unfortunately, I cannot test it right now but following MediaPlayer state diagram, I think that is the right way to do it.

**Comment by oluwabajio** [comment]
if you call the reset(); method, before playing the video, the video wont play and the controls(seekbar, play button, etc wont be updated)

**Comment by rtoshiro** [comment]
Hi @oluwabajio Oh, I see.
In fact, FulllscreenVideoLayout was created just as an example to use FullscreenVideoView. 
I need to rebuild FullscreenVideoLayout as lots of people is tending to use it as a default implementation. 
Until them, I recommend you to update the UI by yourself, extending FullscreenVideoLayout and overriding the reset() melhod. 
It's very simple. You just need to update de seekbar and the progress text:

``` java
@Override
public void reset() {
    super.reset();

    seekBar.setProgress(0);
    textElapsed.setText("00:00");
    textTotal.setText("00:00");
}
```

There were just one problem in that solution. Because of some Android implementations, when we call reset(), the surface is not updated so, for newer Android versions, the video frame is still appearing even when "prepare" is called. I'm still trying to figure out some solution but I haven't found one yet.
So, in that case, instead just calling "reset()", I recommend you to rebuild the FullscreenVideoLayout.
I have tested it and apparently it works well. 
Follow the code I tested:

``` java
public void change(View v) {
    videoLayout.reset();

    FrameLayout.LayoutParams params = (FrameLayout.LayoutParams) videoLayout.getLayoutParams();
    frameLayout.removeView(videoLayout);
    videoLayout = new FullscreenVideoLayout(this);
    videoLayout.setLayoutParams(params);
    frameLayout.addView(videoLayout);

    try {
        Uri videoUri = Uri.parse("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4");
        videoLayout.setVideoURI(videoUri);

    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

Where frameLayout variable is the parent ViewGroup where FullscreenVideoLayout belongs to.

**Comment by rtoshiro** [comment]
Hi @oluwabajio 
Would you mind testing a new version of this lib?
I have uploaded a new snapshot with this fix:
compile 'com.github.rtoshiro.fullscreenvideoview:fullscreenvideoview:1.1.1c-SNAPSHOT'

Just remember to include the repository:
allprojects {
    repositories {
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}

With this update, you only need to call reset() before calling setDataSource again. I hope it helps. I've updated FullscreenVideoLayout to update the UI.
Best

**Comment by oluwabajio** [comment]
i did not import it to my project through gradle, i created the fullscreenvideoview and fullscreenvideoviewlayout as java classes in my project cos i needed to tweak some things in your code, but i will try the new ffix out

Thanks

**Comment by rtoshiro** [comment]
Hi @oluwabajio 
Did you get time to test this fix? 
Thank you.

**Comment by rtoshiro** [comment]
Well. I'm closing it for while

**Comment by Fred117** [comment]
Hello, I have exact the same issue when loading a new video. Your solution with the "compile 'com.github.rtoshiro.fullscreenvideoview:fullscreenvideoview:1.1.1c-SNAPSHOT'" snapshot does not solve the issue. removeView() will help but I don't think that's an nice solution even it works for now. ;) Are you still working on an implementation where reset() works directly?

**Comment by rtoshiro** [comment]
Hi

In fact, I thought it was already solved :)
Have you tested with the last production release 1.1.1 (without SNAPSHOT part)?

Unfortunately I can't test it right now. 
Thank you
Best
T

**Comment by Fred117** [comment]
Hello and thank you very much for your answer. ;)
I have tested it including the following line to my gradle file but that doesn't resolve the problem: 

compile 'com.github.rtoshiro.fullscreenvideoview:fullscreenvideoview:1.1.1'

**Comment by rtoshiro** [comment]
Hi @Fred117 
Sorry for the delay but I'm back now.
I'm testing it but can't find the problem.
Which Android version are you testing it? Do you have the stacktrace error? What happens when you call reset() before setting the new data source?
Thank you very much!
Best
T

**Comment by Fred117** [comment]
Hello and thank you for your answer. It's working now. ;)

**Comment by rtoshiro** [comment]
Nice!

**Comment by saadnawaz1** [comment]
In the reset method; i think you shouldn't release the mediaplayer object. based on the mediaplayer life graph, you can simply call mediaplayer.reset(); after that the state should allow to play next video.. the benefit of the current approach is that you don't have to release the mediaplayer and recreate it.. that should save some time in playing next video.. what do you think?

I tried this by subclassing and it works perfectly fine

**Comment by rtoshiro** [comment]
Hi @saadnawaz1 
Yes, I totally agree.
I just wanted to find a reliable solution ;)
I'll fix that as soon as I can
I have created a new issue #25 
Thx!
Best

**Comment by Maysami** [comment]
hi, I gave the video a second time, then show
Error :  Media Player is not initialized
 at com.github.rtoshiro.view.video.FullscreenVideoView.setVideoURI  ?

help me,
Best

**Comment by RushiMThakker** [comment]
I reset the FullScreenVideoLayout object and then call setVideoURI again but it throws an error:

```
```
 W/System.err: java.lang.IllegalStateException
 W/System.err:     at android.media.MediaPlayer.prepareAsync(Native Method)
 W/System.err:     at appUtils.FullscreenVideoView.prepare(FullscreenVideoView.java:448)
 W/System.err:     at appUtils.FullscreenVideoView.setVideoURI(FullscreenVideoView.java:1029)
 W/System.err:     at adapter.AdapterCreateVideo.updateUrl(AdapterCreateVideo.java:152)
 W/System.err:     at 
 W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6931)
 W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4090)
 W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4137)
 W/System.err:     at android.app.ActivityThread.-wrap20(ActivityThread.java)
 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
 W/System.err:     at android.os.Looper.loop(Looper.java:154)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6123)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```


Could you please help?
```

**Comment by RushiMThakker** [comment]
I fixed it myself making some tweaks in source code. The reason for this error was that prepareAsync in prepare was called before the surface was recreated. The reason for all this was when I called setVideoURI for another video surface was destroyed and was not ready. Surface was created after some time. Another issue was variable videoIsReady. It was not updated when surface was destroyed. Due to all this I made a couple of tweaks to change the flow of library in order to record new video and display it on surface.

I introduced two varaibles in FullScreenVideoView: 

1.   private static int videoLoadingPending=0;
2.   private static Uri pendingUri;

I am uploading updated classes.

[FullscreenVideoView.zip](https://github.com/rtoshiro/FullscreenVideoView/files/1152769/FullscreenVideoView.zip)

**Comment by rtoshiro** [comment]
Hi @RushiMThakker 
Thank you very much. I'll take a look at the code.
I confess i'm not having as much time as I used to. But I'll take a look for sure.

@Maysami 
I didn't understand your question. Did you initialize the object? When it happens?

**Comment by klaszlo8207** [comment]
"Media Player is not initialized" and crash a lot of times, please add a fix to the repo, thanks
